Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-06b21ccaeff8cd686
      SubnetId: subnet-016d76d668e79d8b6
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, from, cloudformation]]