Parameters:
  NameOfService:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m1.small
      - m1.large
  KeyName:
    Description: Name of EC2 login Key
    Type: AWS::EC2::KeyPair::KeyName

Mappings: 
  AMIIDMap: 
    us-east-1:
      MyAMI1: ami-06b21ccaeff8cd686
    us-west-1:
      MyAMI1: ami-0cf4e1fcfd8494d5b
    eu-west-1:
      MyAMI1: ami-00385a401487aefa4 
    ap-northeast-1:
      MyAMI1: ami-03f584e50b2d32776
    ap-southeast-1:
      MyAMI1: ami-04b6019d38ea93034
    
Resources: 
  myEC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !FindInMap [AMIIDMap, !Ref "AWS::Region", MyAMI1]
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      VpcId: vpc-0b1926b3971f85f27
      SubnetId: subnet-016d76d668e79d8b6
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
      SecurityGroupIds:
        - !Ref VprofileSG

  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http from My IP
      VpcId: vpc-0b1926b3971f85f27
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 5.15.115.141/32